name: M.lee Harris Driving Tips
favicon: null
layout_spectrum: 0.7144803868141025
typography_spectrum: 0.2614605827257037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#add7ff'
    - '#bc7500'
    - '#0a1600'
    - '#feb800'
    - '#b70200'
  brandStrength: 0.3086598813533783
  lightness: 0.11770803690887988
  saturation: 0
  rhythmicContrast: 0.6114651781972498
purpose: []
